window.BIBU_DATA={
dayColors:['#d98174','#5f9ea8','#d3a948','#7f9a63','#8b789b','#57969d','#d97d61'],
days:[
{n:1,date:'7/26',dow:'日',title:'抵達札幌・輕鬆適應',sub:'避免太多戶外行程，先休息',drive:false,route:'新千歲機場 → 札幌站 → Solaria',events:[
{time:'07:50',title:'抵達新千歲機場',desc:'入境、取行李；預留約60分鐘。',tag:'航班',place:'New Chitose Airport',travelMin:0,mode:'transit'},
{time:'09:00',title:'前往札幌',desc:'JR／機場巴士；建議先到酒店寄存行李。',tag:'約60–80分鐘',place:'Sapporo Station',travelMin:70,mode:'transit'},
{time:'10:30',title:'札幌站早餐／Brunch',desc:'以室內、近酒店為主，減少長途飛行後負擔。',tag:'輕鬆',place:'Sapporo Station',travelMin:0,mode:'walking'},
{time:'12:00',title:'札幌站・大丸・地下街',desc:'室內行程；按精神狀況自由縮短。',tag:'購物',place:'Daimaru Sapporo',travelMin:5,mode:'walking'},
{time:'15:00',title:'Solaria check-in',desc:'休息、浸浴、整理行李。',tag:'已確認',place:'Solaria Nishitetsu Hotel Sapporo',travelMin:8,mode:'walking'},
{time:'18:00',title:'Soup Curry KING Gateway',desc:'近札幌站；星期日11:30–21:30，無泊車位。',tag:'餐廳',place:'SOUP CURRY KING Gateway Sapporo',travelMin:10,mode:'walking'}]},
{n:2,date:'7/27',dow:'一',title:'札幌市中心・品牌購物',sub:'HUMAN MADE、BEAMS、狸小路',drive:false,route:'札幌站 → 狸小路 → 大通 → Sapporo Factory',events:[
{time:'09:00',title:'特色早餐',desc:'可選二条市場海鮮早餐；想舒服可改酒店早餐。',tag:'早餐',place:'Nijo Market Sapporo',travelMin:20,mode:'transit'},
{time:'11:00',title:'HUMAN MADE SAPPORO',desc:'THE KNOT SAPPORO 1F；營業11:00–19:00。',tag:'購物',place:'HUMAN MADE SAPPORO',travelMin:10,mode:'walking'},
{time:'12:00',title:'狸小路・大通',desc:'午餐與街區散步。',tag:'市中心',place:'Tanukikoji Shopping Street',travelMin:5,mode:'walking'},
{time:'14:00',title:'BEAMS SAPPORO',desc:'南1條西3丁目；一般11:00–20:00。',tag:'購物',place:'BEAMS SAPPORO',travelMin:12,mode:'walking'},
{time:'16:00',title:'大扭蛋場',desc:'首選Sapporo Factory「ガシャポンのデパート」，約600台。',tag:'10:00–21:00',place:'ガシャポンのデパート サッポロファクトリー店',travelMin:18,mode:'transit'},
{time:'19:00',title:'自由晚餐',desc:'按當日位置選居酒屋／海鮮。',tag:'待選',place:'Sapporo Station',travelMin:15,mode:'transit'}]},
{n:3,date:'7/28',dow:'二',title:'小樽一日遊・天狗山',sub:'乘JR往返；三角市場、堺町通及山上景色',drive:false,route:'札幌站 → 小樽站／三角市場 → 小樽運河 → 堺町通 → 天狗山 → 札幌',events:[
{time:'08:15',title:'札幌站出發',desc:'乘JR前往小樽；坐右邊較易看海（視車次）。',tag:'約35–50分鐘',place:'Sapporo Station',travelMin:0,mode:'transit'},
{time:'09:10',title:'三角市場',desc:'小樽站旁先食海鮮早餐；熱門店可能排隊。',tag:'早餐',place:'Otaru Sankaku Market',travelMin:45,mode:'transit'},
{time:'10:30',title:'小樽運河',desc:'沿運河及舊倉庫區散步。',tag:'景點',place:'Otaru Canal',travelMin:12,mode:'walking'},
{time:'11:30',title:'堺町通',desc:'音樂盒堂、玻璃店、LeTAO等；途中安排午餐。',tag:'購物／午餐',place:'Otaru Sakaimachi Street',travelMin:12,mode:'walking'},
{time:'15:30',title:'前往小樽天狗山',desc:'由小樽站乘巴士約20分鐘。',tag:'巴士＋纜車',place:'Otaru Tenguyama Ropeway',travelMin:30,mode:'transit'},
{time:'16:00',title:'小樽天狗山',desc:'欣賞小樽市及石狩灣景色；按天氣決定逗留時間。',tag:'景點',place:'Otaru Tenguyama Ropeway',travelMin:0,mode:'walking'},
{time:'18:15',title:'返回札幌',desc:'天狗山乘巴士回小樽站，再轉JR。',tag:'約60–80分鐘',place:'Sapporo Station',travelMin:70,mode:'transit'},
{time:'20:00',title:'札幌晚餐',desc:'回札幌後按體力選餐廳。',tag:'餐廳',place:'Sapporo Station',travelMin:0,mode:'walking'}]},
{n:4,date:'7/29',dow:'三',title:'札幌場外市場・最後補貨',sub:'為翌日自駕保留體力',drive:false,route:'Solaria → 札幌場外市場 → 札幌站補貨 → Solaria',events:[
{time:'08:00',title:'札幌市中央卸売市場 場外市場',desc:'海鮮早餐及逛市場；各店營業時間不同。',tag:'早餐／市場',place:'Sapporo Central Wholesale Market Curb Market',travelMin:20,mode:'transit'},
{time:'10:30',title:'返回札幌站',desc:'回酒店短暫整理購物清單。',tag:'市內交通',place:'Sapporo Station',travelMin:20,mode:'transit'},
{time:'11:00',title:'札幌站最後補貨',desc:'大丸、Stellar Place及地下街集中處理。',tag:'購物',place:'Daimaru Sapporo',travelMin:5,mode:'walking'},
{time:'13:00',title:'札幌站午餐',desc:'按當日想食及排隊情況選擇。',tag:'自由',place:'Sapporo Station',travelMin:0,mode:'walking'},
{time:'15:00',title:'回酒店整理行李',desc:'確認駕照、國際駕照、護照、租車預約及行李配置。',tag:'重要',place:'Solaria Nishitetsu Hotel Sapporo',travelMin:8,mode:'walking'},
{time:'18:00',title:'我流麵舞 飛燕',desc:'COCONO SUSUKINO 4F；一般11:00–23:00。',tag:'雞白湯',place:'我流麺舞 飛燕 COCONO SUSUKINO',travelMin:15,mode:'transit'},
{time:'20:00',title:'提早休息',desc:'翌日約09:30–10:00取車及長途駕駛。',tag:'休息',place:'Solaria Nishitetsu Hotel Sapporo',travelMin:15,mode:'transit'}]},
{n:5,date:'7/30',dow:'四',title:'取車・札幌 → 富良野',sub:'三笠休息、ふらのや、起司工房後入住',drive:true,route:'札幌 → 道の駅三笠 → ふらのや → 富良野起司工房 → NOZO',events:[
{time:'08:00',title:'酒店早餐／check-out',desc:'Solaria最遲11:00退房；帶齊行李前往取車。',tag:'已確認',place:'Solaria Nishitetsu Hotel Sapporo',travelMin:0,mode:'walking'},
{time:'09:30',title:'Nissan札幌站南口／ASTY取車',desc:'檢查車身、ETC、保險、油種及導航。',tag:'取車',place:'Nissan Rent a Car Sapporo Station South Exit',travelMin:10,mode:'walking'},
{time:'10:15',title:'出發往道の駅 三笠',desc:'由札幌市區經道央道前往三笠。',tag:'約1小時10–25分',place:'道の駅 三笠',travelMin:75,mode:'driving'},
{time:'11:35',title:'道の駅 三笠',desc:'休息、洗手間、小食；普通車約202位，免費。',tag:'停留約30分鐘',place:'道の駅 三笠',travelMin:0,mode:'walking'},
{time:'12:05',title:'三笠 → ふらのや',desc:'沿國道452／38號方向前往富良野。',tag:'約1小時10–25分',place:'ふらのや 富良野',travelMin:75,mode:'driving'},
{time:'13:25',title:'ふらのや午餐',desc:'富良野湯咖喱；1-46 Yayoi-cho，免費泊車。',tag:'11:30–21:00',place:'ふらのや 富良野',travelMin:0,mode:'walking'},
{time:'14:50',title:'前往富良野起司工房',desc:'由ふらのや駕車前往。',tag:'約10–15分鐘',place:'Furano Cheese Factory',travelMin:15,mode:'driving'},
{time:'15:05',title:'富良野起司工房',desc:'夏季09:00–17:00；免費入場及免費泊車。',tag:'景點／甜點',place:'Furano Cheese Factory',travelMin:0,mode:'walking'},
{time:'16:15',title:'前往NOZO Hotel',desc:'起司工房直接前往酒店。',tag:'約10–15分鐘',place:'NOZO Hotel Furano',travelMin:15,mode:'driving'},
{time:'16:30',title:'NOZO Hotel check-in',desc:'門前20位；滿位先向前台查詢後備停車場。',tag:'泊車免費',place:'NOZO Hotel Furano',travelMin:0,mode:'walking'},
{time:'18:30',title:'富良野晚餐',desc:'NOZO周邊按預約及營業情況安排。',tag:'餐廳',place:'Furano Station',travelMin:10,mode:'driving'}]},
{n:6,date:'7/31',dow:'五',title:'美瑛景觀環線・森林精靈露台',sub:'Christmas Tree已刪除；Roller Coaster Road有時間先去',drive:true,route:'NOZO → 四季彩之丘 → 美瑛 → 青池 → 白鬚瀑布 → 新榮之丘 →（有時間：Roller Coaster Road）→ Ningle Terrace → 晚餐',events:[
{time:'08:00',title:'NOZO出發',desc:'帶水、防曬、現金及薄外套。',tag:'自駕',place:'NOZO Hotel Furano',travelMin:0,mode:'driving'},
{time:'08:50',title:'四季彩之丘',desc:'6–9月08:40–17:30；泊車約300位及需收費。',tag:'花田',place:'Shikisai no Oka',travelMin:50,mode:'driving'},
{time:'10:45',title:'前往美瑛午餐區',desc:'由四季彩之丘前往美瑛市中心。',tag:'約20–25分鐘',place:'Biei Station',travelMin:25,mode:'driving'},
{time:'11:15',title:'美瑛午餐',desc:'預留熱門店排隊時間。',tag:'餐廳',place:'Biei Station',travelMin:0,mode:'walking'},
{time:'12:30',title:'美瑛 → 白金青池',desc:'前往白金地區。',tag:'約25–35分鐘',place:'Shirogane Blue Pond',travelMin:35,mode:'driving'},
{time:'13:05',title:'白金青池',desc:'夏季停車場07:00–19:00；普通車¥1,000。',tag:'Map 349 568 888',place:'Shirogane Blue Pond',travelMin:0,mode:'walking'},
{time:'14:00',title:'青池 → 白鬚瀑布',desc:'兩個景點相距很近。',tag:'約5–10分鐘',place:'Shirahige Waterfall Biei',travelMin:10,mode:'driving'},
{time:'14:10',title:'白鬚瀑布',desc:'使用白金觀光中心免費公眾停車場。',tag:'Map 796 182 604',place:'Shirahige Waterfall Biei',travelMin:0,mode:'walking'},
{time:'14:50',title:'前往新榮之丘展望公園',desc:'返回美瑛丘陵地區。',tag:'約30–40分鐘',place:'Shinei no Oka View Park',travelMin:40,mode:'driving'},
{time:'15:30',title:'新榮之丘展望公園',desc:'日落前開放；免費停車約30位。',tag:'景觀',place:'Shinei no Oka View Park',travelMin:0,mode:'walking'},
{time:'16:00',title:'Roller Coaster Road（有時間先去）',desc:'時間不足直接略過；不要停在行車線。',tag:'繞行約10–20分鐘',place:'Roller Coaster Road Kamifurano',travelMin:20,mode:'driving'},
{time:'17:20',title:'森林精靈露台 Ningle Terrace',desc:'安排在晚餐前；商店至19:45。',tag:'免費入場／免費泊車',place:'Ningle Terrace',travelMin:55,mode:'driving'},
{time:'19:00',title:'富良野晚餐',desc:'離開森林精靈露台後再食晚餐。',tag:'餐廳',place:'Furano Station',travelMin:15,mode:'driving'}]},
{n:7,date:'8/1',dow:'六',title:'Farm Tomita・Melon House → 新千歲',sub:'航班21:40；17:30–18:30前完成還車',drive:true,route:'NOZO → Farm Tomita → Tomita Melon House → 新千歲機場還車 → CTS → HND → HKG',events:[
{time:'08:00',title:'早餐・NOZO check-out',desc:'檢查房內及夾萬；行李放上車。',tag:'重要',place:'NOZO Hotel Furano',travelMin:0,mode:'walking'},
{time:'09:05',title:'Farm Tomita',desc:'官方08:30–17:30；免費泊車，勿泊路邊。',tag:'花田',place:'Farm Tomita',travelMin:25,mode:'driving'},
{time:'10:45',title:'Tomita Melon House',desc:'09:00–17:00；品嚐蜜瓜及甜點。',tag:'免費泊車',place:'Tomita Melon House',travelMin:5,mode:'walking'},
{time:'11:45',title:'中富良野午餐／最後整理',desc:'確認還車分店、入油站及航班資料。',tag:'午餐',place:'Nakafurano Station',travelMin:10,mode:'driving'},
{time:'13:00',title:'出發往新千歲機場',desc:'由中富良野前往新千歲機場地區。',tag:'約2小時15–45分',place:'New Chitose Airport',travelMin:150,mode:'driving'},
{time:'15:30',title:'途中休息',desc:'按路況短休；保留塞車緩衝。',tag:'約15–20分鐘',place:'Yuni Parking Area Hokkaido',travelMin:0,mode:'driving'},
{time:'16:30',title:'還車前入油',desc:'按租車要求加滿指定油種並保留單據。',tag:'重要',place:'Gas station near New Chitose Airport',travelMin:45,mode:'driving'},
{time:'17:30',title:'Nissan新千歲機場店還車',desc:'目標17:30–18:30前完成；預留接駁。',tag:'還車',place:'Nissan Rent a Car New Chitose Airport',travelMin:10,mode:'driving'},
{time:'18:30',title:'新千歲機場',desc:'晚餐、手信、安檢。',tag:'機場',place:'New Chitose Airport',travelMin:15,mode:'transit'},
{time:'21:40',title:'NH988前往羽田',desc:'23:30抵達；轉乘NH813回港。',tag:'航班',place:'New Chitose Airport',travelMin:0,mode:'walking'}]}
],
places:[
{type:'餐廳',name:'Soup Curry KING Gateway',area:'札幌站',desc:'抵達日最方便的湯咖喱選擇。',facts:['周末11:30–21:30','沒有泊車位'],q:'SOUP CURRY KING Gateway Sapporo',url:'https://www.soupcurry-king.shop/'},
{type:'購物',name:'HUMAN MADE SAPPORO',area:'狸小路',desc:'THE KNOT SAPPORO 1樓。',facts:['11:00–19:00'],q:'HUMAN MADE SAPPORO'},
{type:'購物',name:'BEAMS SAPPORO',area:'大通',desc:'札幌市中心兩層店。',facts:['一般11:00–20:00'],q:'BEAMS SAPPORO'},
{type:'購物',name:'ガシャポンのデパート',area:'Sapporo Factory',desc:'大型扭蛋場，約600個機台。',facts:['10:00–21:00'],q:'ガシャポンのデパート サッポロファクトリー店'},
{type:'餐廳',name:'我流麵舞 飛燕',area:'札幌／薄野',desc:'雞白湯拉麵；COCONO SUSUKINO分店。',facts:['11:00–23:00'],q:'我流麺舞 飛燕 COCONO SUSUKINO'},
{type:'景點',name:'小樽運河',area:'小樽',desc:'經典運河與舊倉庫景觀。',facts:['由小樽站步行約10分鐘'],q:'Otaru Canal',url:'https://otaru.gr.jp/'},
{type:'景點',name:'堺町通',area:'小樽',desc:'玻璃、音樂盒、甜點及手信集中地。',facts:['步行遊覽'],q:'Otaru Sakaimachi Street'},
{type:'景點',name:'小樽天狗山',area:'小樽',desc:'纜車欣賞小樽市、港口與石狩灣。',facts:['免費停車'],q:'Otaru Tenguyama Ropeway'},
{type:'市場',name:'札幌場外市場',area:'札幌',desc:'海鮮早餐、乾貨及北海道手信。',facts:['建議早上到達'],q:'Sapporo Central Wholesale Market Curb Market'},
{type:'餐廳',name:'ふらのや',area:'富良野',desc:'湯咖喱／日式咖喱。',facts:['11:30–21:00','免費泊車'],q:'ふらのや 富良野'},
{type:'休息站',name:'道の駅 三笠',area:'三笠',desc:'札幌往富良野中途休息。',facts:['普通車約202位／免費'],q:'道の駅 三笠'},
{type:'景點',name:'富良野起司工房',area:'富良野',desc:'參觀乳製品與芝士製作。',facts:['09:00–17:00','免費泊車約120位'],q:'Furano Cheese Factory'},
{type:'景點',name:'Farm Tomita',area:'中富良野',desc:'薰衣草與花田；早到較舒服。',facts:['08:30–17:30','免費泊車'],q:'Farm Tomita',url:'https://www.farm-tomita.co.jp/en/'},
{type:'餐廳',name:'Tomita Melon House',area:'中富良野',desc:'蜜瓜、雪糕及甜點。',facts:['09:00–17:00','免費泊車'],q:'Tomita Melon House'},
{type:'景點',name:'四季彩之丘',area:'美瑛',desc:'大面積彩色花田。',facts:['08:40–17:30','泊車收費'],q:'Shikisai no Oka',url:'https://www.shikisainooka.jp/en/'},
{type:'景點',name:'白金青池',area:'美瑛白金',desc:'藍色池水與落葉松景觀。',facts:['普通車¥1,000','MAP 349 568 888'],q:'Shirogane Blue Pond',url:'https://www.biei-hokkaido.jp/en/facility/shirogane-blue-pond'},
{type:'景點',name:'白鬚瀑布',area:'美瑛白金',desc:'由橋上觀賞，與青池很近。',facts:['公眾停車場免費','MAP 796 182 604'],q:'Shirahige Waterfall Biei'},
{type:'景點',name:'新榮之丘展望公園',area:'美瑛',desc:'欣賞美瑛丘陵及十勝岳。',facts:['免費泊車約30位'],q:'Shinei no Oka View Park'},
{type:'景點',name:'Roller Coaster Road',area:'上富良野',desc:'只在時間充足時順路停留。',facts:['不要停在行車線','勿進入私人農地'],q:'Roller Coaster Road Kamifurano'},
{type:'購物',name:'森林精靈露台',area:'富良野',desc:'森林木屋手作商店；晚餐前到訪。',facts:['11:00–19:45','免費泊車'],q:'Ningle Terrace'}],
flights:[['NH814','香港 → 羽田','7/25 23:55—04:55'],['NH987','羽田 → 新千歲','7/26 06:20—07:50'],['NH988','新千歲 → 羽田','8/1 21:40—23:30'],['NH813','羽田 → 香港','8/2 01:35—05:15']],
hotels:[['Solaria Nishitetsu Hotel Sapporo','7/26—7/30','15:00入住｜7/30 11:00退房','Solaria Nishitetsu Hotel Sapporo'],['NOZO Hotel Furano','7/30—8/1','北の峰町14-38｜免費泊車','NOZO Hotel Furano']],
checklist:['護照','國際駕駛許可證＋香港駕照','租車預約確認','旅遊保險','酒店及航班確認','下載離線地圖','現金／信用卡／交通卡','手機充電器／尿袋','水、防曬、薄外套','雨具']
};
